package jugador;

import javax.swing.JButton;

/**
 */
public class Main extends javax.swing.JFrame {

    private Cliente cliente;
    private JButton[][][] botones = new JButton[9][3][3];
    /*
    Constructor donde generamos una matriz de botones, que represneta el tablero del juego
    */
    public Main() {
        try {
            initComponents();
            botones[0][0][0] = M11;
            botones[0][0][1] = M12;
            botones[0][0][2] = M13;
            botones[0][1][0] = M21;
            botones[0][1][1] = M22;
            botones[0][1][2] = M23;
            botones[0][2][0] = M31;
            botones[0][2][1] = M32;
            botones[0][2][2] = M33;
            
            botones[1][0][0] = M15;
            botones[1][0][1] = M16;
            botones[1][0][2] = M17;
            botones[1][1][0] = M24;
            botones[1][1][1] = M25;
            botones[1][1][2] = M26;
            botones[1][2][0] = M34;
            botones[1][2][1] = M35;
            botones[1][2][2] = M36;
            
            botones[2][0][0] = M18;
            botones[2][0][1] = M19;
            botones[2][0][2] = M20;
            botones[2][1][0] = M27;
            botones[2][1][1] = M28;
            botones[2][1][2] = M29;
            botones[2][2][0] = M37;
            botones[2][2][1] = M38;
            botones[2][2][2] = M39;
            
            botones[3][0][0] = M51;
            botones[3][0][1] = M52;
            botones[3][0][2] = M53;
            botones[3][1][0] = M54;
            botones[3][1][1] = M56;
            botones[3][1][2] = M30;
            botones[3][2][0] = M40;
            botones[3][2][1] = M41;
            botones[3][2][2] = M42;
            
            botones[4][0][0] = M50;
            botones[4][0][1] = M57;
            botones[4][0][2] = M55;
            botones[4][1][0] = M46;
            botones[4][1][1] = M58;
            botones[4][1][2] = M59;
            botones[4][2][0] = M47;
            botones[4][2][1] = M48;
            botones[4][2][2] = M49;
            
            botones[5][0][0] = M45;
            botones[5][0][1] = M61;
            botones[5][0][2] = M60;
            botones[5][1][0] = M62;
            botones[5][1][1] = M63;
            botones[5][1][2] = M64;
            botones[5][2][0] = M65;
            botones[5][2][1] = M43;
            botones[5][2][2] = M44;
            
            botones[6][0][0] = M68;
            botones[6][0][1] = M70;
            botones[6][0][2] = M69;
            botones[6][1][0] = M71;
            botones[6][1][1] = M73;
            botones[6][1][2] = M83;
            botones[6][2][0] = M84;
            botones[6][2][1] = M85;
            botones[6][2][2] = M86;
            
            botones[7][0][0] = M67;
            botones[7][0][1] = M74;
            botones[7][0][2] = M72;
            botones[7][1][0] = M75;
            botones[7][1][1] = M76;
            botones[7][1][2] = M90;
            botones[7][2][0] = M91;
            botones[7][2][1] = M92;
            botones[7][2][2] = M66;
            
            botones[8][0][0] = M89;
            botones[8][0][1] = M78;
            botones[8][0][2] = M77;
            botones[8][1][0] = M79;
            botones[8][1][1] = M80;
            botones[8][1][2] = M81;
            botones[8][2][0] = M82;
            botones[8][2][1] = M87;
            botones[8][2][2] = M88;
            
            cliente= new Cliente(this);
            Thread hilo = new Thread(cliente);
            hilo.start();
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton7 = new javax.swing.JButton();
        M14 = new javax.swing.JButton();
        M11 = new javax.swing.JButton();
        M13 = new javax.swing.JButton();
        M12 = new javax.swing.JButton();
        M21 = new javax.swing.JButton();
        M22 = new javax.swing.JButton();
        M23 = new javax.swing.JButton();
        M31 = new javax.swing.JButton();
        M32 = new javax.swing.JButton();
        M33 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        lbTurno = new javax.swing.JLabel();
        M24 = new javax.swing.JButton();
        M34 = new javax.swing.JButton();
        M35 = new javax.swing.JButton();
        M36 = new javax.swing.JButton();
        M15 = new javax.swing.JButton();
        M16 = new javax.swing.JButton();
        M17 = new javax.swing.JButton();
        M25 = new javax.swing.JButton();
        M26 = new javax.swing.JButton();
        M18 = new javax.swing.JButton();
        M19 = new javax.swing.JButton();
        M27 = new javax.swing.JButton();
        M28 = new javax.swing.JButton();
        M29 = new javax.swing.JButton();
        M37 = new javax.swing.JButton();
        M38 = new javax.swing.JButton();
        M39 = new javax.swing.JButton();
        M20 = new javax.swing.JButton();
        M30 = new javax.swing.JButton();
        M40 = new javax.swing.JButton();
        M41 = new javax.swing.JButton();
        M42 = new javax.swing.JButton();
        M43 = new javax.swing.JButton();
        M44 = new javax.swing.JButton();
        M45 = new javax.swing.JButton();
        M46 = new javax.swing.JButton();
        M47 = new javax.swing.JButton();
        M48 = new javax.swing.JButton();
        M49 = new javax.swing.JButton();
        M50 = new javax.swing.JButton();
        M51 = new javax.swing.JButton();
        M52 = new javax.swing.JButton();
        M53 = new javax.swing.JButton();
        M54 = new javax.swing.JButton();
        M55 = new javax.swing.JButton();
        M56 = new javax.swing.JButton();
        M57 = new javax.swing.JButton();
        M58 = new javax.swing.JButton();
        M59 = new javax.swing.JButton();
        M60 = new javax.swing.JButton();
        M61 = new javax.swing.JButton();
        M62 = new javax.swing.JButton();
        M63 = new javax.swing.JButton();
        M64 = new javax.swing.JButton();
        M65 = new javax.swing.JButton();
        M66 = new javax.swing.JButton();
        M67 = new javax.swing.JButton();
        M68 = new javax.swing.JButton();
        M69 = new javax.swing.JButton();
        M70 = new javax.swing.JButton();
        M71 = new javax.swing.JButton();
        M72 = new javax.swing.JButton();
        M73 = new javax.swing.JButton();
        M74 = new javax.swing.JButton();
        M75 = new javax.swing.JButton();
        M76 = new javax.swing.JButton();
        M77 = new javax.swing.JButton();
        M78 = new javax.swing.JButton();
        M79 = new javax.swing.JButton();
        M80 = new javax.swing.JButton();
        M81 = new javax.swing.JButton();
        M82 = new javax.swing.JButton();
        M83 = new javax.swing.JButton();
        M84 = new javax.swing.JButton();
        M85 = new javax.swing.JButton();
        M86 = new javax.swing.JButton();
        M87 = new javax.swing.JButton();
        M88 = new javax.swing.JButton();
        M89 = new javax.swing.JButton();
        M90 = new javax.swing.JButton();
        M91 = new javax.swing.JButton();
        M92 = new javax.swing.JButton();

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jugador/O.png"))); // NOI18N

        M14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                M14ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TicTacToe NetoSolis");
        setResizable(false);

        M11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                M11ActionPerformed(evt);
            }
        });

        M13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                M13ActionPerformed(evt);
            }
        });

        M12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                M12ActionPerformed(evt);
            }
        });

        M21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                M21ActionPerformed(evt);
            }
        });

        M22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                M22ActionPerformed(evt);
            }
        });

        M23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                M23ActionPerformed(evt);
            }
        });

        M31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                M31ActionPerformed(evt);
            }
        });

        M32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                M32ActionPerformed(evt);
            }
        });

        M33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                M33ActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        jButton1.setText("Reiniciar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        lbTurno.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        lbTurno.setText("Tu turno: ");

        M24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                M24ActionPerformed(evt);
            }
        });

        M34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                M34ActionPerformed(evt);
            }
        });

        M35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                M35ActionPerformed(evt);
            }
        });

        M36.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                M36ActionPerformed(evt);
            }
        });

        M15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                M15ActionPerformed(evt);
            }
        });

        M16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                M16ActionPerformed(evt);
            }
        });

        M17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                M17ActionPerformed(evt);
            }
        });

        M25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                M25ActionPerformed(evt);
            }
        });

        M26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                M26ActionPerformed(evt);
            }
        });

        M18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                M18ActionPerformed(evt);
            }
        });

        M19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                M19ActionPerformed(evt);
            }
        });

        M27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                M27ActionPerformed(evt);
            }
        });

        M28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                M28ActionPerformed(evt);
            }
        });

        M29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                M29ActionPerformed(evt);
            }
        });

        M37.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                M37ActionPerformed(evt);
            }
        });

        M38.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                M38ActionPerformed(evt);
            }
        });

        M39.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                M39ActionPerformed(evt);
            }
        });

        M20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                M20ActionPerformed(evt);
            }
        });

        M30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                M30ActionPerformed(evt);
            }
        });

        M40.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                M40ActionPerformed(evt);
            }
        });

        M41.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                M41ActionPerformed(evt);
            }
        });

        M42.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                M42ActionPerformed(evt);
            }
        });

        M43.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                M43ActionPerformed(evt);
            }
        });

        M44.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                M44ActionPerformed(evt);
            }
        });

        M45.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                M45ActionPerformed(evt);
            }
        });

        M46.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                M46ActionPerformed(evt);
            }
        });

        M47.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                M47ActionPerformed(evt);
            }
        });

        M48.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                M48ActionPerformed(evt);
            }
        });

        M49.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                M49ActionPerformed(evt);
            }
        });

        M50.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                M50ActionPerformed(evt);
            }
        });

        M51.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                M51ActionPerformed(evt);
            }
        });

        M52.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                M52ActionPerformed(evt);
            }
        });

        M53.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                M53ActionPerformed(evt);
            }
        });

        M54.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                M54ActionPerformed(evt);
            }
        });

        M55.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                M55ActionPerformed(evt);
            }
        });

        M56.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                M56ActionPerformed(evt);
            }
        });

        M57.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                M57ActionPerformed(evt);
            }
        });

        M58.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                M58ActionPerformed(evt);
            }
        });

        M59.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                M59ActionPerformed(evt);
            }
        });

        M60.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                M60ActionPerformed(evt);
            }
        });

        M61.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                M61ActionPerformed(evt);
            }
        });

        M62.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                M62ActionPerformed(evt);
            }
        });

        M63.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                M63ActionPerformed(evt);
            }
        });

        M64.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                M64ActionPerformed(evt);
            }
        });

        M65.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                M65ActionPerformed(evt);
            }
        });

        M66.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                M66ActionPerformed(evt);
            }
        });

        M67.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                M67ActionPerformed(evt);
            }
        });

        M68.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                M68ActionPerformed(evt);
            }
        });

        M69.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                M69ActionPerformed(evt);
            }
        });

        M70.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                M70ActionPerformed(evt);
            }
        });

        M71.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                M71ActionPerformed(evt);
            }
        });

        M72.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                M72ActionPerformed(evt);
            }
        });

        M73.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                M73ActionPerformed(evt);
            }
        });

        M74.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                M74ActionPerformed(evt);
            }
        });

        M75.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                M75ActionPerformed(evt);
            }
        });

        M76.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                M76ActionPerformed(evt);
            }
        });

        M77.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                M77ActionPerformed(evt);
            }
        });

        M78.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                M78ActionPerformed(evt);
            }
        });

        M79.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                M79ActionPerformed(evt);
            }
        });

        M80.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                M80ActionPerformed(evt);
            }
        });

        M81.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                M81ActionPerformed(evt);
            }
        });

        M82.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                M82ActionPerformed(evt);
            }
        });

        M83.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                M83ActionPerformed(evt);
            }
        });

        M84.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                M84ActionPerformed(evt);
            }
        });

        M85.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                M85ActionPerformed(evt);
            }
        });

        M86.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                M86ActionPerformed(evt);
            }
        });

        M87.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                M87ActionPerformed(evt);
            }
        });

        M88.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                M88ActionPerformed(evt);
            }
        });

        M89.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                M89ActionPerformed(evt);
            }
        });

        M90.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                M90ActionPerformed(evt);
            }
        });

        M91.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                M91ActionPerformed(evt);
            }
        });

        M92.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                M92ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(M68, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(M71, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(M84, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(M70, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(M73, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(M85, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(M86, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(M83, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(M69, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(61, 61, 61)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(M91, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(M67, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(M75, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(M92, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(M74, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(M76, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(M72, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(M90, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(M66, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(M82, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(M79, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(M89, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(M78, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(M80, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(M87, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbTurno)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(M51, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(M54, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(M40, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(M53, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(M56, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(M41, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(M42, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(M30, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGap(19, 19, 19)
                                                .addComponent(M52, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(61, 61, 61)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(M47, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(M50, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(M58, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(M48, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(M57, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(M59, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(M55, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(M46, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(M49, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(M11, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
                                            .addComponent(M21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(M31, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(M12, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                                            .addComponent(M22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(M32, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(M33, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
                                                    .addComponent(M23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGap(19, 19, 19)
                                                .addComponent(M13, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(61, 61, 61)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(M34, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
                                            .addComponent(M15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(M25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(M35, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
                                            .addComponent(M17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(M26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(M16, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
                                            .addComponent(M24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(M36, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                .addGap(58, 58, 58)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(M37, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
                                            .addComponent(M27, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(M20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(M38, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(M19, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
                                                .addComponent(M28, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                        .addGap(22, 22, 22)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(M18, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
                                            .addComponent(M29, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(M39, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(M65, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(M62, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(M45, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(M61, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(M63, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
                                            .addComponent(M43, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(M64, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(M44, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(M60, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(M77, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(M81, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(M88, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGap(44, 44, 44))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(M16, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(M24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(M11, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
                                            .addComponent(M12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(M13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(18, 18, 18))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(M15, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(M17, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(M22, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(M21, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(M23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(M25, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(M26, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(M35, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
                            .addComponent(M34, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(M33, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(M32, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(M31, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(M36, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(26, 26, 26))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(M19, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(M20, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(M18, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(M28, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                            .addComponent(M27, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(M29, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(M38, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(M37, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(M39, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(M61, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(M45, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(M60, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(M63, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                                .addComponent(M62, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(M64, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(M65, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(M44, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(M43, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(M55, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(M46, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(M51, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(M53, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(M52, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(M50, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(M57, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(M56, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(M54, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(M30, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(M58, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(M59, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(M48, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(M47, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(M42, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(M41, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(M40, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(M49, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(79, 79, 79)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(M78, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(M89, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(M77, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(M80, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(M79, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(M81, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(M82, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(M88, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(M87, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(M72, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(M90, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(M68, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(M70, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(M69, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(M67, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(M74, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(M73, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(M71, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(M83, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(M75, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(M76, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(M92, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(M91, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(M86, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(M85, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(M84, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(M66, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lbTurno)
                        .addGap(31, 31, 31))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void M11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_M11ActionPerformed
        enviarTurno(0, 0, 0 );
    }//GEN-LAST:event_M11ActionPerformed

    private void M13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_M13ActionPerformed
        enviarTurno(0, 0, 2 );
    }//GEN-LAST:event_M13ActionPerformed

    private void M12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_M12ActionPerformed
        enviarTurno(0, 0, 1 );
    }//GEN-LAST:event_M12ActionPerformed

    private void M14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_M14ActionPerformed

    }//GEN-LAST:event_M14ActionPerformed

    private void M21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_M21ActionPerformed
        enviarTurno(0, 1, 0 );
    }//GEN-LAST:event_M21ActionPerformed

    private void M22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_M22ActionPerformed
        enviarTurno(0, 1, 1 );
    }//GEN-LAST:event_M22ActionPerformed

    private void M23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_M23ActionPerformed
        enviarTurno(0, 1, 2 );
    }//GEN-LAST:event_M23ActionPerformed

    private void M31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_M31ActionPerformed
        enviarTurno(0, 2, 0 );
    }//GEN-LAST:event_M31ActionPerformed

    private void M32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_M32ActionPerformed
        enviarTurno(0, 2, 1 );
    }//GEN-LAST:event_M32ActionPerformed

    private void M33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_M33ActionPerformed
        enviarTurno(0, 2, 2 );
    }//GEN-LAST:event_M33ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new Main().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void M24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_M24ActionPerformed
        enviarTurno(1,1,0);
    }//GEN-LAST:event_M24ActionPerformed

    private void M34ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_M34ActionPerformed
        enviarTurno(1,2,0);
    }//GEN-LAST:event_M34ActionPerformed

    private void M35ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_M35ActionPerformed
        enviarTurno(1,2,1);
    }//GEN-LAST:event_M35ActionPerformed

    private void M36ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_M36ActionPerformed
        enviarTurno(1,2,2);
    }//GEN-LAST:event_M36ActionPerformed

    private void M15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_M15ActionPerformed
        enviarTurno(1,0,0);
    }//GEN-LAST:event_M15ActionPerformed

    private void M16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_M16ActionPerformed
        enviarTurno(1,0,1);
    }//GEN-LAST:event_M16ActionPerformed

    private void M17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_M17ActionPerformed
        enviarTurno(1,0,2);
    }//GEN-LAST:event_M17ActionPerformed

    private void M25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_M25ActionPerformed
        enviarTurno(1,1,1);
    }//GEN-LAST:event_M25ActionPerformed

    private void M26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_M26ActionPerformed
        enviarTurno(1,1,2);  
    }//GEN-LAST:event_M26ActionPerformed

    private void M18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_M18ActionPerformed
        enviarTurno(1,1,2);
    }//GEN-LAST:event_M18ActionPerformed

    private void M19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_M19ActionPerformed
        enviarTurno(2,0,0);
    }//GEN-LAST:event_M19ActionPerformed

    private void M27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_M27ActionPerformed
        enviarTurno(2,1,0);
    }//GEN-LAST:event_M27ActionPerformed

    private void M28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_M28ActionPerformed
        enviarTurno(2,1,1);
    }//GEN-LAST:event_M28ActionPerformed

    private void M29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_M29ActionPerformed
        enviarTurno(2,1,2);
    }//GEN-LAST:event_M29ActionPerformed

    private void M37ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_M37ActionPerformed
        enviarTurno(2,2,0);
    }//GEN-LAST:event_M37ActionPerformed

    private void M38ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_M38ActionPerformed
        enviarTurno(2,2,1);
    }//GEN-LAST:event_M38ActionPerformed

    private void M39ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_M39ActionPerformed
        enviarTurno(2,2,2);
    }//GEN-LAST:event_M39ActionPerformed

    private void M20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_M20ActionPerformed
        enviarTurno(2,0,2);
    }//GEN-LAST:event_M20ActionPerformed

    private void M30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_M30ActionPerformed
        enviarTurno(3,1,2);
    }//GEN-LAST:event_M30ActionPerformed

    private void M40ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_M40ActionPerformed
        enviarTurno(3,2,0);
    }//GEN-LAST:event_M40ActionPerformed

    private void M41ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_M41ActionPerformed
        enviarTurno(3,2,1);
    }//GEN-LAST:event_M41ActionPerformed

    private void M42ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_M42ActionPerformed
        enviarTurno(3,2,2);
    }//GEN-LAST:event_M42ActionPerformed

    private void M43ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_M43ActionPerformed
        enviarTurno(5,2,1);
    }//GEN-LAST:event_M43ActionPerformed

    private void M44ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_M44ActionPerformed
        enviarTurno(5,2,2);
    }//GEN-LAST:event_M44ActionPerformed

    private void M45ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_M45ActionPerformed
        enviarTurno(5,0,0);
    }//GEN-LAST:event_M45ActionPerformed

    private void M46ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_M46ActionPerformed
        enviarTurno(4,1,0);
    }//GEN-LAST:event_M46ActionPerformed

    private void M47ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_M47ActionPerformed
        enviarTurno(4,2,0);
    }//GEN-LAST:event_M47ActionPerformed

    private void M48ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_M48ActionPerformed
        enviarTurno(4,2,1);
    }//GEN-LAST:event_M48ActionPerformed

    private void M49ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_M49ActionPerformed
        enviarTurno(4,2,2);
    }//GEN-LAST:event_M49ActionPerformed

    private void M50ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_M50ActionPerformed
        enviarTurno(4,0,0);
    }//GEN-LAST:event_M50ActionPerformed

    private void M51ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_M51ActionPerformed
        enviarTurno(3,0,0);
    }//GEN-LAST:event_M51ActionPerformed

    private void M52ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_M52ActionPerformed
        enviarTurno(3,0,1);
    }//GEN-LAST:event_M52ActionPerformed

    private void M53ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_M53ActionPerformed
        enviarTurno(3,0,2);
    }//GEN-LAST:event_M53ActionPerformed

    private void M54ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_M54ActionPerformed
        enviarTurno(3,1,0);
    }//GEN-LAST:event_M54ActionPerformed

    private void M55ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_M55ActionPerformed
        enviarTurno(4,0,2);
    }//GEN-LAST:event_M55ActionPerformed

    private void M56ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_M56ActionPerformed
        enviarTurno(3,1,1);
    }//GEN-LAST:event_M56ActionPerformed

    private void M57ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_M57ActionPerformed
        enviarTurno(4,0,1);
    }//GEN-LAST:event_M57ActionPerformed

    private void M58ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_M58ActionPerformed
        enviarTurno(4,1,1);
    }//GEN-LAST:event_M58ActionPerformed

    private void M59ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_M59ActionPerformed
        enviarTurno(4,1,2);
    }//GEN-LAST:event_M59ActionPerformed

    private void M60ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_M60ActionPerformed
        enviarTurno(5,0,2);
    }//GEN-LAST:event_M60ActionPerformed

    private void M61ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_M61ActionPerformed
        enviarTurno(5,0,1);
    }//GEN-LAST:event_M61ActionPerformed

    private void M62ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_M62ActionPerformed
        enviarTurno(5,1,0);
    }//GEN-LAST:event_M62ActionPerformed

    private void M63ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_M63ActionPerformed
        enviarTurno(5,1,1);
    }//GEN-LAST:event_M63ActionPerformed

    private void M64ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_M64ActionPerformed
        enviarTurno(5,1,2);
    }//GEN-LAST:event_M64ActionPerformed

    private void M65ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_M65ActionPerformed
        enviarTurno(5,2,0);
    }//GEN-LAST:event_M65ActionPerformed

    private void M66ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_M66ActionPerformed
        enviarTurno(7,2,2);
    }//GEN-LAST:event_M66ActionPerformed

    private void M67ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_M67ActionPerformed
        enviarTurno(7,0,0);
    }//GEN-LAST:event_M67ActionPerformed

    private void M68ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_M68ActionPerformed
        enviarTurno(6,0,0);
    }//GEN-LAST:event_M68ActionPerformed

    private void M69ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_M69ActionPerformed
        enviarTurno(6,0,2);
    }//GEN-LAST:event_M69ActionPerformed

    private void M70ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_M70ActionPerformed
        enviarTurno(6,0,1);
    }//GEN-LAST:event_M70ActionPerformed

    private void M71ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_M71ActionPerformed
        enviarTurno(6,1,0);
    }//GEN-LAST:event_M71ActionPerformed

    private void M72ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_M72ActionPerformed
        enviarTurno(7,0,2);
    }//GEN-LAST:event_M72ActionPerformed

    private void M73ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_M73ActionPerformed
        enviarTurno(6,1,1);
    }//GEN-LAST:event_M73ActionPerformed

    private void M74ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_M74ActionPerformed
        enviarTurno(7,0,1);
    }//GEN-LAST:event_M74ActionPerformed

    private void M75ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_M75ActionPerformed
        enviarTurno(7,1,0);
    }//GEN-LAST:event_M75ActionPerformed

    private void M76ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_M76ActionPerformed
        enviarTurno(7,1,1);
    }//GEN-LAST:event_M76ActionPerformed

    private void M77ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_M77ActionPerformed
        enviarTurno(8,0,2);
    }//GEN-LAST:event_M77ActionPerformed

    private void M78ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_M78ActionPerformed
        enviarTurno(8,0,1);
    }//GEN-LAST:event_M78ActionPerformed

    private void M79ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_M79ActionPerformed
        enviarTurno(8,1,0);
    }//GEN-LAST:event_M79ActionPerformed

    private void M80ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_M80ActionPerformed
        enviarTurno(8,1,1);
    }//GEN-LAST:event_M80ActionPerformed

    private void M81ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_M81ActionPerformed
        enviarTurno(8,1,2);
    }//GEN-LAST:event_M81ActionPerformed

    private void M82ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_M82ActionPerformed
        enviarTurno(8,2,0);
    }//GEN-LAST:event_M82ActionPerformed

    private void M83ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_M83ActionPerformed
        enviarTurno(6,1,2);
    }//GEN-LAST:event_M83ActionPerformed

    private void M84ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_M84ActionPerformed
        enviarTurno(6,2,0);
    }//GEN-LAST:event_M84ActionPerformed

    private void M85ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_M85ActionPerformed
        enviarTurno(6,2,1);
    }//GEN-LAST:event_M85ActionPerformed

    private void M86ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_M86ActionPerformed
        enviarTurno(6,2,2);
    }//GEN-LAST:event_M86ActionPerformed

    private void M87ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_M87ActionPerformed
        enviarTurno(8,2,1);
    }//GEN-LAST:event_M87ActionPerformed

    private void M88ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_M88ActionPerformed
        enviarTurno(8,2,2);
    }//GEN-LAST:event_M88ActionPerformed

    private void M89ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_M89ActionPerformed
        enviarTurno(8,0,0);
    }//GEN-LAST:event_M89ActionPerformed

    private void M90ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_M90ActionPerformed
        enviarTurno(7,1,2);
    }//GEN-LAST:event_M90ActionPerformed

    private void M91ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_M91ActionPerformed
        enviarTurno(7,2,0);
    }//GEN-LAST:event_M91ActionPerformed

    private void M92ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_M92ActionPerformed
        enviarTurno(7,2,1);
    }//GEN-LAST:event_M92ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton M11;
    private javax.swing.JButton M12;
    private javax.swing.JButton M13;
    private javax.swing.JButton M14;
    private javax.swing.JButton M15;
    private javax.swing.JButton M16;
    private javax.swing.JButton M17;
    private javax.swing.JButton M18;
    private javax.swing.JButton M19;
    private javax.swing.JButton M20;
    private javax.swing.JButton M21;
    private javax.swing.JButton M22;
    private javax.swing.JButton M23;
    private javax.swing.JButton M24;
    private javax.swing.JButton M25;
    private javax.swing.JButton M26;
    private javax.swing.JButton M27;
    private javax.swing.JButton M28;
    private javax.swing.JButton M29;
    private javax.swing.JButton M30;
    private javax.swing.JButton M31;
    private javax.swing.JButton M32;
    private javax.swing.JButton M33;
    private javax.swing.JButton M34;
    private javax.swing.JButton M35;
    private javax.swing.JButton M36;
    private javax.swing.JButton M37;
    private javax.swing.JButton M38;
    private javax.swing.JButton M39;
    private javax.swing.JButton M40;
    private javax.swing.JButton M41;
    private javax.swing.JButton M42;
    private javax.swing.JButton M43;
    private javax.swing.JButton M44;
    private javax.swing.JButton M45;
    private javax.swing.JButton M46;
    private javax.swing.JButton M47;
    private javax.swing.JButton M48;
    private javax.swing.JButton M49;
    private javax.swing.JButton M50;
    private javax.swing.JButton M51;
    private javax.swing.JButton M52;
    private javax.swing.JButton M53;
    private javax.swing.JButton M54;
    private javax.swing.JButton M55;
    private javax.swing.JButton M56;
    private javax.swing.JButton M57;
    private javax.swing.JButton M58;
    private javax.swing.JButton M59;
    private javax.swing.JButton M60;
    private javax.swing.JButton M61;
    private javax.swing.JButton M62;
    private javax.swing.JButton M63;
    private javax.swing.JButton M64;
    private javax.swing.JButton M65;
    private javax.swing.JButton M66;
    private javax.swing.JButton M67;
    private javax.swing.JButton M68;
    private javax.swing.JButton M69;
    private javax.swing.JButton M70;
    private javax.swing.JButton M71;
    private javax.swing.JButton M72;
    private javax.swing.JButton M73;
    private javax.swing.JButton M74;
    private javax.swing.JButton M75;
    private javax.swing.JButton M76;
    private javax.swing.JButton M77;
    private javax.swing.JButton M78;
    private javax.swing.JButton M79;
    private javax.swing.JButton M80;
    private javax.swing.JButton M81;
    private javax.swing.JButton M82;
    private javax.swing.JButton M83;
    private javax.swing.JButton M84;
    private javax.swing.JButton M85;
    private javax.swing.JButton M86;
    private javax.swing.JButton M87;
    private javax.swing.JButton M88;
    private javax.swing.JButton M89;
    private javax.swing.JButton M90;
    private javax.swing.JButton M91;
    private javax.swing.JButton M92;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel lbTurno;
    // End of variables declaration//GEN-END:variables

    
    public void cambioTexto(String cad){
        lbTurno.setText(cad);       
    }
    
    public JButton[][][] getBotones(){
        return botones;
    }
    
    //Cuando se preciona un boton enviamos los datos de la jugada al servidor (fila y columna del boton precionado)
    public void enviarTurno(int f,int c, int t){
        cliente.enviarTurno(f, c, t );
    }

    
}

